#env:
#	py -3.12 -m venv beeware-venv
#	.\beeware-venv\Scripts\Activate.bat
#	python -m pip install briefcase

prod: create build package

dev:
	briefcase dev

create:
	briefcase create

build:
	briefcase build

package:
	briefcase package